function data = ReadExcelData()
%IMPORTFILE Import data from a spreadsheet
%   data = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   data = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   data = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   data = importfile('ParameterConfig.xlsx','Sheet1',1,12);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2015/02/12 18:41:31

%% Input handling

% If no sheet is specified, read first sheet
    sheet = 1;


% read 12 data points
    startRow = 1;
    endRow = 12;

%% Import the data
data = xlsread('ParameterConfig.xlsx', sheet, sprintf('B%d:B%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread('ParameterConfig.xlsx', sheet, sprintf('B%d:B%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

